
 const KEYCODE_ENTER = 13;
 const KEYCODE_ESC = 27;
 const MOUSE_LEFT_CLICK_EVENT = 0;
 const AJAX_CALL_DELAY = 1000;
 const POPUP_FADE_OUT = 150;
 const POPUP_LEAVING_CLASS = 'fade-out';
 const POPUP_ENTERING_CLASS = 'bounce-in';


export {
	KEYCODE_ENTER,
	KEYCODE_ESC,
	MOUSE_LEFT_CLICK_EVENT,
	AJAX_CALL_DELAY,
	POPUP_FADE_OUT,
	POPUP_LEAVING_CLASS,
	POPUP_ENTERING_CLASS,
}